Add gitops version subcommand
rhd-gitops-example/gitops-cli pull request #9
Opened 2020-09-15 15:45 UTC by wtam2018

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
/kind feature
> /kind flake
> /kind code-refactoring

**What does this PR do / why we need it**:

This PR implements a "version" sub-command for gitops command.   What it does is that it output the version with the following information so that the user can easy find out what revision the gitops is built from.

```<tag>-<n-commits>-g<commit-sha>-<dirty>```

<tag> is the tag if tag has been created
<n-commints> is the number of commits since the tag if tag has been created
g - is for git
<commit-sha> is the same commit sha
<dirty> is shown if the command binary was built with local file changes.

E.g.
```
[wtam@localhost test-gitops-cli]$ ./gitops version
gitops version v0.0.9-1-g7fa007f-dirty
```

**Have you updated the necessary documentation?**

See https://github.com/rhd-gitops-example/docs

[ ] Updated

**Which issue(s) this PR fixes**:

Fixes #?
https://issues.redhat.com/browse/GITOPS-310

**How to test changes / Special notes to the reviewer**:
Manually tested.

2020-09-15 16:07 UTC, bigkevmcd requested changes

2020-09-15 16:07 UTC, bigkevmcd commented on pkg/cmd/root.go
> -		Use:   "gitops-cli",
You probably want to rename `cmd/gitops-cli` with this change.

2020-09-15 16:07 UTC, bigkevmcd commented on pkg/cmd/version/version.go
> +// RecommendedCommandName is the recommended environment command name.
Not sure what `environment` means in this context?

2020-09-15 16:07 UTC, bigkevmcd commented on pkg/cmd/version/version.go
> +// NewCmd creates a new environment command
Or here?

These could probably be `version` ?

2020-09-15 16:07 UTC, bigkevmcd commented on pkg/cmd/version/version.go
> +		Short: "Get gitops command version",
How about...

```Print the version information``` as it's not really "getting" anything?

2020-09-15 19:40 UTC, wtam2018 commented on pkg/cmd/root.go
> -		Use:   "gitops-cli",
renamed root.go to gitops.go

2020-09-15 19:40 UTC, wtam2018 commented on pkg/cmd/version/version.go
> +// RecommendedCommandName is the recommended environment command name.
removed "environment" (bad copy and past)

2020-09-15 19:40 UTC, wtam2018 commented on pkg/cmd/version/version.go
> +// NewCmd creates a new environment command
removed "environment" (bad copy and past)

2020-09-15 19:41 UTC, wtam2018 commented on pkg/cmd/version/version.go
> +		Short: "Get gitops command version",
Replaced text as suggested.

2020-09-16 09:42 UTC, bigkevmcd approved these changes

2020-09-16 09:42 UTC, merged